
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        numpy.version: '1.16'
      Python36:
        python.version: '3.6'
        numpy.version: '1.16'
      Python37:
        python.version: '3.7'
        numpy.version: '1.16'
      Python38:
        python.version: '3.8'
        numpy.version: '1.16'
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to path
  - script: conda create -y -n n88 -c babesler -c conda-forge conda-build vtkbone setuptools scipy nose netCDF4 python=$(python.version) numpy=$(numpy.version)
    displayName: Setup conda
  - script: |
      source activate n88
      python setup.py install
    displayName: Build
  - script: |
      source activate n88
      nosetests tests
    displayName: Test
  - script: |
        source activate n88
        conda-build -c babesler -c conda-forge conda-recipe/n88tools/ --variants "{'python': ['$(python.version)'], 'numpy': ['$(numpy.version)']}"
    displayName: Conda build
  - task: CopyFiles@2
    inputs:
        sourceFolder: /usr/share/miniconda/envs/n88/conda-bld/linux-64/
        contents: '*.tar.bz2'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy conda build
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: n88tools-Linux-$(python.version)
    displayName: Publish artifact
